source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Password Manager' do
  pod 'Qonversion', '~> 2.0.0'
  pod 'FBSDKCoreKit/Swift'
  pod 'Amplitude-iOS', '~> 4.9.3'
  pod 'Purchases', '3.5.2'
  pod 'NVActivityIndicatorView'
  pod 'SwiftRater'
  pod 'Firebase/Analytics'
  pod 'Firebase/RemoteConfig'
  pod 'KeychainAccess'
  pod 'AppLocker', :git => 'https://github.com/Ryasnoy/AppLocker.git', :commit => '411725a'
end

target 'AutoFillExtension' do
  pod 'KeychainAccess'
end
