source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Password Manager' do
  pod 'Qonversion', '~> 2.0.0'
  pod 'FBSDKCoreKit'
  pod 'FBAudienceNetwork'
  pod 'Amplitude-iOS', '~> 4.9.3'
  pod 'Purchases', '3.5.2'
  pod 'NVActivityIndicatorView'
  pod 'SwiftRater'
  pod 'Firebase/Analytics'
  pod 'Firebase/RemoteConfig'
  pod 'KeychainAccess'
  pod 'lottie-ios'
  pod 'AppsFlyerFramework'
end

target 'AutoFillExtension' do
  pod 'KeychainAccess'
end
